# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodInventoryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodInventoryApp
	pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'

  # Optionally, include the Swift extensions if you're using Swift.
#  pod 'FirebaseFirestoreSwift'

  target 'FoodInventoryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
